Facebook project/Facebook project/Models/Comment.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Facebook_project.Models
{
    public class Comment
    {
        [Required]
        public int PostID { get; set; }

        [Required]
        public string UserID { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime Time { get; set; }

        public bool isRemoved { get; set; }

        //[JsonIgnore]
        [ForeignKey("UserID")]
        public virtual AppUser User { get; set; }

        //[JsonIgnore]
        [ForeignKey("PostID")]
        public virtual Post Post { get; set; }

        public string Text { get; set; }

        public string PictureURL { get; set; }

    }
}

Facebook project/Facebook project/Models/Likes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Facebook_project.Models
{
    public class Like
    {
        [Required]
        [Key, Column(Order = 0)]
        public string UserID { get; set; }

        [Required]
        [Key, Column(Order = 1)]
        public int PostID { get; set; }

        public bool isLiked { get; set; }

        //[JsonIgnore]
        [ForeignKey("UserID")]
        public virtual AppUser User { get; set; }

        //[JsonIgnore]
        [ForeignKey("PostID")]
        public virtual Post Post { get; set; }
    }
}

Facebook project/Facebook project/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Facebook_project.Data;
using Facebook_project.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Facebook_project.Repositories;
using Facebook_project.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Facebook_project.Controllers
{
    public class PostsController : Controller
    {
        //private readonly ApplicationDbContext _context;
        PostRepository _context;
        public PostsController(PostRepository context)
        {
            _context = context;
        }

        // GET: Posts
        public IActionResult Index()
        {
            var repo = _context.GetPosts();
            return View(repo.ToList());
        }

        
        // GET: Posts/Create
        public IActionResult Create()
        {
           // ViewData["PublisherId"] = new SelectList(_context.AppUsers, "Id", "Id");
            return PartialView();
        }

        
        [HttpPost]
        [Authorize]
        //[ValidateAntiForgeryToken]
        public IActionResult AddPost(IFormFile file)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var picName = "";

                /////checking image
                if (HttpContext.Request.Form.Files.Any())
                {
                    var img = HttpContext.Request.Form.Files[0];
                    string pic = Path.GetFileName(img.FileName);
                    byte[] array;


                    using (MemoryStream ms = new MemoryStream())
                    {
                        img.CopyTo(ms);
                        array = ms.GetBuffer();
                        picName = $"{Guid.NewGuid()}.jpg";
                        var str = Path.Combine(Environment.CurrentDirectory, "wwwroot//PostsPics", picName);
                        System.IO.File.WriteAllBytes(str, array);
                    }
                }
                /////////////////////

                if (HttpContext.Request.Form.Keys.Any())
                {
                    Microsoft.Extensions.Primitives.StringValues post = "";
                    Microsoft.Extensions.Primitives.StringValues PID = "";
                    HttpContext.Request.Form.TryGetValue("postText", out post);

                    string PostText = post.ToString();

                    Post newpPost = new Post()
                    {
                        Date = DateTime.Now,
                        isDeleted = false,
                        Text = PostText,
                        PublisherId = userId
                    };

                    if (picName != "")
                        newpPost.PictureURL = picName;


                    _context.CreatePost(newpPost);

                    var respPost = _context.GetPostByUserAndDate(newpPost.PublisherId, newpPost.Date);

                   

                    return PartialView("~/Views/Posts/_Post.cshtml",respPost);

                }
            }

            return Json("error");
        }

        // GET: Posts/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = _context.GetPostByID(id);
            if (post == null)
            {
                return NotFound();
            }
            //ViewData["PublisherId"] = new SelectList(_context.AppUsers, "Id", "Id", post.PublisherId);
            return View(post);
        }


        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            _context.DeletePost(id);
            return RedirectToAction(nameof(Index));
        }
        
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult Like(int id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                _context.AddLike(userId, id);
            }
            return RedirectToAction(nameof(Index), "Home");
        }

        public IActionResult Dislike(int id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                _context.Dislike(userId, id);
            }
            return RedirectToAction(nameof(Index), "Home");
        }

        public IActionResult LikesModal(int id)
        {
            List<AppUser> Users = _context.GetPostLikers(id);
            return PartialView("_Likes",Users);
        }
       
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public IActionResult AddComment(IFormFile file)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var picName = "";

                /////checking image
                if (HttpContext.Request.Form.Files.Any())
                {
                    var img = HttpContext.Request.Form.Files[0];
                    string pic = Path.GetFileName(img.FileName);
                    byte[] array;


                    using (MemoryStream ms = new MemoryStream())
                    {
                        img.CopyTo(ms);
                        array = ms.GetBuffer();
                        picName = $"{Guid.NewGuid()}.jpg";
                        var str = Path.Combine(Environment.CurrentDirectory, "wwwroot//CommentsPics", picName);
                        System.IO.File.WriteAllBytes(str, array);
                    }
                }
                /////////////////////

                if (HttpContext.Request.Form.Keys.Any())
                {
                    Microsoft.Extensions.Primitives.StringValues cmnt = "";
                    Microsoft.Extensions.Primitives.StringValues PID = "";
                    HttpContext.Request.Form.TryGetValue("comment", out cmnt);
                    HttpContext.Request.Form.TryGetValue("PostId", out PID);

                    string PostId = PID.ToString();
                    string Comment = cmnt.ToString();

                    Comment comment = new Comment()
                    {
                        PostID = int.Parse(PostId),
                        Text = Comment,
                        Time = DateTime.Now,
                        UserID = userId,
                        isRemoved = false
                        
                    };
                    if (picName != "")
                        comment.PictureURL = picName;


                    _context.AddComment(comment);

                    var respComment = _context.GetComment(comment.UserID, comment.PostID, comment.Time.ToString());
                    return PartialView("~/Views/Posts/_Comment.cshtml", respComment);
                }
            }

            return Json("error");
        }

        public IActionResult DeletePost(int Id)
        {
            if (_context.DeletePost(Id))
                return Json("success");
            return Json("error"); 
        }

        //[HttpPost]
        public IActionResult DeleteComment(string objId)
        {
            var arr = objId.Split("*");
            var postId = int.Parse(arr[1]);
            var publisherId = arr[2];
            var date = arr[3];

            if (_context.DeleteComment(postId, publisherId, date))
                return Json("success");
            return Json("error");
        }

        public IActionResult ConfirmDeleteModal(string objId)
        {
            return PartialView("_ComfirmDelete", objId);
        }
        public IActionResult EditPostModal(int Id)
        {
            var post = _context.GetPostByID(Id);

            if(post != null)
                return PartialView("_EditPost", post);
            return Json("error");
        }
        public IActionResult EditCommentModal(string objId)
        {
            var arr = objId.Split("*");
            var postId = int.Parse(arr[1]);
            var publisherId = arr[2];
            var date = arr[3];

            var comment = _context.GetComment(publisherId, postId, date);

            if (comment != null)
                return PartialView("_EditComment", comment);
            return Json("error");
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult EditPost(IFormFile file)
        {
            

            if (HttpContext.Request.Form.Keys.Any())
            {
                if (HttpContext.Request.Form.Keys.Contains("postId"))
                {

                    Microsoft.Extensions.Primitives.StringValues postText = "";
                    Microsoft.Extensions.Primitives.StringValues PID = "";
                    Microsoft.Extensions.Primitives.StringValues removeImg = "";
                    HttpContext.Request.Form.TryGetValue("postText", out postText);
                    HttpContext.Request.Form.TryGetValue("postId", out PID);
                    HttpContext.Request.Form.TryGetValue("removeImg", out removeImg);




                    string PostText = postText.ToString();
                    int PostID =int.Parse(PID);
                    string picName = "";
                    bool removeImage = bool.Parse(removeImg);

Facebook project/Facebook project/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Facebook_project.Models;
using Facebook_project.Models.ViewModels;
using Facebook_project.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Facebook_project.Controllers
{
    public class UsersController : Controller
    {

        AppUserRepository _context;
        public UsersController(AppUserRepository db)
        {
            _context = db;
        }
        public IActionResult UserPage(string id)
        {
            var user = _context.GetUserByid(id);
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                ViewBag.CurrentUser = _context.GetUserByid(userId);
            }
            return View(user);
        }
        public IActionResult EditUserDataModal()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var user = _context.GetUserByid(userId);
                return PartialView("EditUserDataModal", user);
            }
            return Json("error");
        }

        [HttpPost]
        [Authorize]
        public IActionResult EditUserData(IFormFile file)
        {
            if (HttpContext.Request.Form.Keys.Any())
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                if (claim != null)
                {
                    Microsoft.Extensions.Primitives.StringValues fullname = "";
                    Microsoft.Extensions.Primitives.StringValues bio = "";
                    Microsoft.Extensions.Primitives.StringValues birthdate = "";
                    Microsoft.Extensions.Primitives.StringValues gender = "";

                    HttpContext.Request.Form.TryGetValue("fullname", out fullname);
                    HttpContext.Request.Form.TryGetValue("bio", out bio);
                    HttpContext.Request.Form.TryGetValue("birthdate", out birthdate);
                    HttpContext.Request.Form.TryGetValue("gender", out gender);

                    var userId = claim.Value;
                    var status = _context.isBlocked(userId);
                    if (!status)
                    {
                        AppUser user = new AppUser
                        {
                            Id = userId,
                            FullName = fullname.ToString(),
                            Bio = bio.ToString(),
                            BirthDate = DateTime.Parse(birthdate.ToString()),
                            Gender = (Gender)Enum.Parse(typeof(Gender), gender.ToString())
                        };
                        _context.UpdateUserInfo(user);
                        return Json(user);
                    }
                }
            }

            return Json("error");
        }

        public IActionResult EditUserImage(IFormFile file)
        {

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var status = _context.isBlocked(userId);
                Microsoft.Extensions.Primitives.StringValues removeImg = "";

                HttpContext.Request.Form.TryGetValue("removeImg", out removeImg);

                string picName = "";
                bool removeImage = bool.Parse(removeImg);

                /////checking image
                if (HttpContext.Request.Form.Files.Any())
                {
                    var img = HttpContext.Request.Form.Files[0];
                    string pic = Path.GetFileName(img.FileName);
                    byte[] array;


                    using (MemoryStream ms = new MemoryStream())
                    {
                        img.CopyTo(ms);
                        array = ms.GetBuffer();
                        picName = $"{Guid.NewGuid()}.jpg";
                        var str = Path.Combine(Environment.CurrentDirectory, "wwwroot//ProfilPics", picName);
                        System.IO.File.WriteAllBytes(str, array);
                    }
                }

                var respImg = _context.UpdateImageUser(userId, picName, removeImage);

                ResponseViewModel response = new ResponseViewModel()
                {
                    PicURL = respImg.PhotoURL,

                };
                return Json(response);
                //return Json(new { response=response, Url="UserPage/"+userId});
            }
            return Json("error");
        }

        public IActionResult EditUserImageModal()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var user = _context.GetUserByid(userId);
                return PartialView("EditUserImageModal", user);
            }
            return Json("error");
        }

        public IActionResult ChangeRelationStatus(string Id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var components = Id.Split("*");
                var receiverId = components[0];
                var status = components[1];
                var userId = claim.Value;
                _context.ChangeRelation(userId,receiverId,status);
                return Json("success");
            }
            return Json("error");
        }
    } 
}

Facebook project/Facebook project/Views/Posts/_ComfirmDelete.cshtml
@model string

    <div id="ConfirmDeletePopupContainer" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"></div>

                <h2>Confirm Delete ?</h2>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-4">

                            @{
                                if (Model.Contains("comment"))
                                {
                                    <input class="btn btn-info" type="button" name="Yes" value="Yes" onclick="DeleteComment('@Model')" />
                                }
                                else if (int.TryParse(Model,out _))
                                {
                                    <input class="btn btn-info" type="button" name="Yes" value="Yes" onclick="DeletePost(@Model)" />
                                }
                            }

                            <input class="btn btn-danger" onclick="ToggleConfirmDeleteModal()" type="button" name="No" value="No" />
                        </div>
                    </div>
                </div>

                <div class="modal-footer"></div>


            </div>
        </div>
    </div>

Facebook project/Facebook project/Views/Posts/_Comment.cshtml
@model Comment
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;

@{

    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
    var userId = claim.Value;

    if (!Model.isRemoved)
    {
        string CommentID = $"comment*{Model.PostID}*{Model.UserID}*{Model.Time.ToString().Replace(" ", "")}";

        <li id="@CommentID" class="comment">
            <div class="media">

                <div class="container-fluid">

                    <div class="row">
                        <div class="col-md-12">
                            <div class="post-header">
                                <div class="Comment-left-section">
                                    <div class="media-left">
                                        <a asp-controller="Users" asp-action="UserPage" asp-route-id="@Model.UserID">
                                            <img class="media-object photo-profile rounded-circle"
                                                 src="~/ProfilPics/@Model.User.PhotoURL"
                                                 width="32" height="32" alt="..." style="border-radius:50%">
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <a id="publisherNameLabel" asp-controller="Users" asp-action="UserPage" asp-route-id="@Model.User.Id">
                                            <h4 class="media-heading">@Model.User.FullName</h4>
                                        </a>
                                        <p class="anchor-time">@Model.Time</p>
                                    </div>
                                </div>
                                <div class="Comment-right-section">
                                    @if (userId == Model.UserID)
                                    {
                                        <i class="fa fa-trash ml-2 fa-lg" onclick="ConfirmDeleteModal('@CommentID')"></i>
                                        <i class="fa fa-edit ml-2 fa-lg" onclick="EditCommentModal('@CommentID')"></i>
                                    }
                                </div>
                            </div>
                        </div>

                        <div class="col-xs-1"></div>
                        <div class="col-xs-8">
                            <section class="comment-body">
                                @{
                                    string CommentTextDiv = $"CommentTextDiv*{Model.PostID}*{Model.UserID}*{Model.Time.ToString().Replace(" ", "")}";
                                    <div id="@CommentTextDiv" class="col-12">
                                        @if (Model.Text != null && Model.Text != "")
                                        {
                                            <p class="col-form-label">@Model.Text</p>
                                        }
                                    </div>
                                }
                                @{
                                    string CommentImgDiv = $"CommentImgDiv*{Model.PostID}*{Model.UserID}*{Model.Time.ToString().Replace(" ", "")}";

                                    <div id="@CommentImgDiv" class="col-12">
                                        @if (Model.PictureURL != null && Model.PictureURL != "")
                                        {
                                            <img class="img-fluid img-thumbnail" src="~/CommentsPics/@Model.PictureURL" />
                                        }
                                    </div>

                                }
                            </section>
                        </div>

                    </div>
                </div>
            </div>
        </li>


    }
}

Facebook project/Facebook project/Views/Posts/_Create.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;

@model Facebook_project.Models.Post
@{
    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
    var userId = claim.Value;

    <div class="col-md-12 col-xs-12">
        <div class="well well-sm well-social-post">
            <form method="post" enctype="multipart/form-data">

                <textarea id="postText" class="form-control" placeholder="What's on your mind ?"></textarea>
                

                <div class='list-inline post-actions post-header'>

                    <div class="creatPostImgSelectorDiv">
                        <label id="custom-file-upload" class="custom-file-upload">
                            <input class="btn fa fa-camera" type="file" name="file" id="creatPostImgSelector" style="display:none" onchange="readURL(this,'#createPostImg')">
                            <i class="btn fa fa-camera fa-lg"></i>
                        </label>
                    </div>

                    <div id="createPostImgDiv" class="col-12">
                        <img id="createPostImg" class="img-fluid" src="" />
                    </div>

                    <div class=''>
                        <input type="button" value="Create" class="btn btn-primary" onclick="addPost()" />
                    </div>

                </div>
            </form>
        </div>
    </div>

}

<script>

    function addPost() {
        var postText = document.querySelector("#postText").value;

        var data = new FormData();
        var files = $("#creatPostImgSelector").get(0).files;

        if (files.length > 0) {
            data.append("postImg", files[0]);
        }
        else if (postText.trim() == "") {
                alert("Cannot create an empty post");
                return;
        }

        data.append("postText", postText);

		$.ajax({
			type: "POST",
			url: '@Url.Action("AddPost","Posts")',//"Posts/AddPost",
			data: data,
			processData: false,
			contentType: false,

			success: function (response) {

				document.querySelector("#postsContainer").insertAdjacentHTML('afterbegin', response);

				document.querySelector("#postText").value = "";
                document.querySelector('#creatPostImgSelector').remove();
                document.querySelector('#custom-file-upload').innerHTML = '<input class="btn fa fa-camera" type="file" name="file" id="creatPostImgSelector" style="display:none" onchange="readURL(this,createPostImg)"/> <i class="btn fa fa-camera fa-lg"></i>';
				document.querySelector('#createPostImg').src = "";
			},
			error: function (response) {
				alert("Error submiting Post");
			}
		});

        $("#PopupContainer").modal("toggle");
	}

</script>

Facebook project/Facebook project/Views/Posts/_EditComment.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;

@model Facebook_project.Models.Comment
@{
    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
    var userId = claim.Value;

    <div id="EditCommentPopupContainer" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"></div>

                <h2>Edit Comment</h2>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-4">
                            
                            <form method="post" enctype="multipart/form-data">
                                <div class="text-danger"></div>

                                <div class="form-group">
                                    <label class="control-label">New Post</label>
                                    <textarea asp-for="@Model.Text" id="EditCommentText"></textarea>
                                </div>

                                <div class="col-12">
                                    @{
                                        if (Model.PictureURL != null)
                                        {
                                            <img id="EditCommentImg" class="img-fluid img-thumbnail" src="~/CommentsPics/@Model.PictureURL" />
                                        }
                                        else
                                        {
                                            <img id="EditCommentImg" class="img-fluid img-thumbnail" src="" />
                                        }
                                    }
                                </div>

                                <div id="commentImgSelectorDiv" class="form-group">
                                    <input type="file" name="file" id="commentImgSelector" style="width: 100%;" onchange="readURL(this,'#EditCommentImg')" />
                                </div>

                                <div class="form-group">
                                    <input type="button" value="Edit" data-dismiss="modal" class="btn btn-primary" onclick="EditComment('@Model.PostID','@Model.UserID','@Model.Time.ToString()')" />
                                </div>

                                <div class="form-group">
                                    <i class="fas fa-backspace fa-lg" onclick="ResetFile('commentImgSelector','commentImgSelectorDiv','EditCommentImg')"></i>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div>
                        @Html.ActionLink("Back to List", "Index","Home")
                    </div>

                </div>

                <div class="modal-footer"></div>


            </div>
        </div>
    </div>



}

<script>

    

</script>

Facebook project/Facebook project/Views/Posts/_Likes.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;
@*@inject SignInManager<AppUser> SignInManager
    @inject UserManager<AppUser> UserManager*@

@model IEnumerable<Facebook_project.Models.AppUser>
@{
    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
    var userId = claim.Value;

    <div id="LikesPopupContainer" class="modal fade LikesModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"></div>

                <h2>Likes</h2>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-md-4">

                            @foreach (var item in Model)
                            {
                                <img src="~/ProfilPics/@item.PhotoURL" class="img-fluid searchResult" />
                                <a href="#">@item.FullName</a>
                            }
                        </div>
                    </div>

                    <div>
                        @Html.ActionLink("Back to List", "Index","Home")
                    </div>

                </div>

                <div class="modal-footer"></div>


            </div>
        </div>
    </div>



}