Facebook project/Facebook project/Models/Friend.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Facebook_project.Models
{
    public enum Status
    {
        RequestPending,
        Blocked,//for future work
        RequestConfirmed,
        FriendRemoved,
        RequestCanceled,
        RequestRejected
    }
    public class Friend
    {
        [Key, Column(Order = 0)]
        public string senderUserID { get; set; }

        [Key, Column(Order = 1)]
        public string receiverUserID { get; set; }
        [Required]
        public Status Status { get; set; }
        [JsonIgnore]
        [ForeignKey("senderUserID")]
        public virtual AppUser SenderUser { get; set; }
        [JsonIgnore]
        [ForeignKey("receiverUserID")]
        public virtual AppUser RecieverUser { get; set; }
    }
}

Facebook project/Facebook project/Controllers/FriendsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Facebook_project.Models;
using Facebook_project.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Facebook_project.Controllers
{
    public class FriendsController : Controller
    {
        FriendsRepository _context;
        public FriendsController(FriendsRepository db)
        {
            _context = db;
        }
        public IActionResult FriendRequestsModal()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            //Get User ID
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;

                var users = _context.GetFriendRequests(userId);
                return PartialView("_FriendRequests", users);
            }
            return RedirectToAction(nameof(Index));//nameof(Index)
        }

        [HttpPost]
        public IActionResult RejectRequest(string id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                _context.changeRequestStatus(id, userId, Status.RequestRejected);
            }
            return Json("success");
        }

        [HttpPost]
        public IActionResult AcceptRequest(string id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                _context.changeRequestStatus(id, userId, Status.RequestConfirmed);
            }
            return Json("success");
        }

        public IActionResult Search(string Id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                //var userId = claim.Value;
                var result = _context.Search(Id);
                return Json(result);
            }
            return Json("error");
        }
        public IActionResult FriendsModal()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;

                var users = _context.GetFriends(userId);
                return PartialView("_FriendsModal", users);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Facebook project/Facebook project/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Facebook_project.Models;
using Facebook_project.Models.ViewModels;
using Facebook_project.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Facebook_project.Controllers
{
    public class UsersController : Controller
    {

        AppUserRepository _context;
        public UsersController(AppUserRepository db)
        {
            _context = db;
        }
        public IActionResult UserPage(string id)
        {
            var user = _context.GetUserByid(id);
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                ViewBag.CurrentUser = _context.GetUserByid(userId);
            }
            return View(user);
        }
        public IActionResult EditUserDataModal()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var user = _context.GetUserByid(userId);
                return PartialView("EditUserDataModal", user);
            }
            return Json("error");
        }

        [HttpPost]
        [Authorize]
        public IActionResult EditUserData(IFormFile file)
        {
            if (HttpContext.Request.Form.Keys.Any())
            {
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                if (claim != null)
                {
                    Microsoft.Extensions.Primitives.StringValues fullname = "";
                    Microsoft.Extensions.Primitives.StringValues bio = "";
                    Microsoft.Extensions.Primitives.StringValues birthdate = "";
                    Microsoft.Extensions.Primitives.StringValues gender = "";

                    HttpContext.Request.Form.TryGetValue("fullname", out fullname);
                    HttpContext.Request.Form.TryGetValue("bio", out bio);
                    HttpContext.Request.Form.TryGetValue("birthdate", out birthdate);
                    HttpContext.Request.Form.TryGetValue("gender", out gender);

                    var userId = claim.Value;
                    var status = _context.isBlocked(userId);
                    if (!status)
                    {
                        AppUser user = new AppUser
                        {
                            Id = userId,
                            FullName = fullname.ToString(),
                            Bio = bio.ToString(),
                            BirthDate = DateTime.Parse(birthdate.ToString()),
                            Gender = (Gender)Enum.Parse(typeof(Gender), gender.ToString())
                        };
                        _context.UpdateUserInfo(user);
                        return Json(user);
                    }
                }
            }

            return Json("error");
        }

        public IActionResult EditUserImage(IFormFile file)
        {

            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var status = _context.isBlocked(userId);
                Microsoft.Extensions.Primitives.StringValues removeImg = "";

                HttpContext.Request.Form.TryGetValue("removeImg", out removeImg);

                string picName = "";
                bool removeImage = bool.Parse(removeImg);

                /////checking image
                if (HttpContext.Request.Form.Files.Any())
                {
                    var img = HttpContext.Request.Form.Files[0];
                    string pic = Path.GetFileName(img.FileName);
                    byte[] array;


                    using (MemoryStream ms = new MemoryStream())
                    {
                        img.CopyTo(ms);
                        array = ms.GetBuffer();
                        picName = $"{Guid.NewGuid()}.jpg";
                        var str = Path.Combine(Environment.CurrentDirectory, "wwwroot//ProfilPics", picName);
                        System.IO.File.WriteAllBytes(str, array);
                    }
                }

                var respImg = _context.UpdateImageUser(userId, picName, removeImage);

                ResponseViewModel response = new ResponseViewModel()
                {
                    PicURL = respImg.PhotoURL,

                };
                return Json(response);
                //return Json(new { response=response, Url="UserPage/"+userId});
            }
            return Json("error");
        }

        public IActionResult EditUserImageModal()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var userId = claim.Value;
                var user = _context.GetUserByid(userId);
                return PartialView("EditUserImageModal", user);
            }
            return Json("error");
        }

        public IActionResult ChangeRelationStatus(string Id)
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var components = Id.Split("*");
                var receiverId = components[0];
                var status = components[1];
                var userId = claim.Value;
                _context.ChangeRelation(userId,receiverId,status);
                return Json("success");
            }
            return Json("error");
        }
    } 
}

Facebook project/Facebook project/Views/Friends/_FriendRequests.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;
@*@inject SignInManager<AppUser> SignInManager
    @inject UserManager<AppUser> UserManager*@

@model IEnumerable<Facebook_project.Models.AppUser>
@{
    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
    var userId = claim.Value;

    <div id="FriendRequestsPopupContainer" class="modal fade LikesModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"></div>

                <h2>Friend Requests</h2>
                <div class="modal-body">

                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-12">
                                <ul class="list-group">

                                    @foreach (var item in Model)
                                    {
                                        string RequestId = $"request{item.Id}";

                                        <li id="@RequestId" class="list-group-item d-flex justify-content-between align-items-center">
                                            <div class="ModalList">
                                                <div class="col-8" style="padding:10px">
                                                    <a href="/Users/UserPage/@item.Id">
                                                        <img src="/ProfilPics/@item.PhotoURL" class="img-fluid searchResult">
                                                    </a>
                                                    <a href="/Users/UserPage/@item.Id">@item.FullName</a>
                                                </div>
                                                <div>
                                                    <input type="button" class="btn btn-primary Accept" value="Accept" onclick="FriendRequest(this,'@item.Id')" />
                                                    <input type="button" class="btn btn-danger Reject" value="Reject" onclick="FriendRequest(this,'@item.Id')" />
                                                </div>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div>
                        @Html.ActionLink("Back to List", "Index", "Home")
                    </div>

                </div>

                <div class="modal-footer"></div>


            </div>
        </div>
    </div>



}

<script>

    function FriendRequest(caller, ReqUserId) {

        var RID = '#request' + ReqUserId;
        var RequestElement = document.querySelector(RID);
        if (caller.classList.contains("Accept")) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("AcceptRequest","Friends")/' + ReqUserId,
                success: function () {
                    RequestElement.remove();
                },
                error: function () {
                    alert("Error while Accepting Request");
                }
            });
        }
        else if (caller.classList.contains("Reject")) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("RejectRequest","Friends")/' + ReqUserId,
                success: function () {
                    RequestElement.remove();
                },
                error: function () {
                    alert("Error while Rejecting Request");
                }
            });
        }
    }

</script>

Facebook project/Facebook project/Views/Friends/_FriendsModal.cshtml
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims;
@*@inject SignInManager<AppUser> SignInManager
    @inject UserManager<AppUser> UserManager*@

@model IEnumerable<Facebook_project.Models.AppUser>
@{
    var claimsIdentity = (ClaimsIdentity)this.User.Identity;
    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
    var userId = claim.Value;

    <div id="FriendsPopupContainer" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header"></div>

                <h2>My Friends</h2>
                <div class="modal-body">



                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-12">
                                <ul class="list-group">

                                    @foreach (var item in Model)
                                    {
                                        string LiId = "Item" + item.Id;
                                        <li id="@LiId" class="list-group-item d-flex justify-content-between align-items-center">
                                            <div class="ModalList">
                                                <div class="col-8" style="padding:10px">
                                                    <a href="/Users/UserPage/@item.Id">
                                                        <img src="/ProfilPics/@item.PhotoURL" class="img-fluid searchResult">
                                                    </a>
                                                    <a href="/Users/UserPage/@item.Id">@item.FullName</a>
                                                </div>
                                                <div>
                                                    <input type="button" class="btn btn-danger Reject" value="Remove" onclick="RemoveFriend('@item.Id')" />

                                                </div>
                                            </div>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>


                    @*<div class="row">
            <div class="col-10">

                @foreach (var item in Model)
                {
                    string RequestId = $"request{item.Id}";

                    <div id="@RequestId">
                        <img src="~/ProfilPics/@item.PhotoURL" class="img-fluid searchResult" />
                        <a href="/Users/UserPage/@item.Id">@item.FullName</a>
                        <input type="button" class="btn btn-danger Reject" value="Remove" onclick="FriendRequest(this,'@item.Id')" />
                    </div>
                }
            </div>
        </div>*@

                    <div>
                        @Html.ActionLink("Back to List", "Index", "Home")
                    </div>

                </div>

                <div class="modal-footer"></div>


            </div>
        </div>
    </div>



}

<script>

    function RemoveFriend(UserId) {

        var RID = '#Item' + UserId;
        var UserElement = document.querySelector(RID);


        //var userid = document.querySelector('#UserId').value;
            var concat = `${UserId}*${3}`;
            $.ajax({
                type: "GET",
                url: '@Url.Action("ChangeRelationStatus","Users")/' + concat,
                success: function () {
                        
                    UserElement.remove();
                },
                error: function () {
                    alert("Error");
                }
            });
    }

</script>